AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: CreditSim - Simple Serverless Architecture v6

Resources:

########################
# Frontend (React) 
########################
  FrontendBucket:
    Type: AWS::S3::Bucket
    Properties:
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      # Asegurar CORS
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders: ["*"]
            AllowedMethods: [GET, HEAD]
            AllowedOrigins: ["*"]
            MaxAge: 3600

  FrontendBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref FrontendBucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal: '*'
            Action: s3:GetObject
            Resource: !Sub '${FrontendBucket.Arn}/*'

  CloudFront:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        DefaultRootObject: index.html
        Origins:
          - Id: Frontend
            DomainName: !GetAtt FrontendBucket.RegionalDomainName
            S3OriginConfig:
              OriginAccessIdentity: ''
        DefaultCacheBehavior:
          TargetOriginId: Frontend
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods: [GET, HEAD]
          CachedMethods: [GET, HEAD]
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none

########################
# API Gateway
########################

  CreditSimApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: CreditSimAPI
      StageName: prod
      EndpointConfiguration: REGIONAL
      Cors:
        AllowMethods: "'GET,POST,OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"
        AllowCredentials: false
      Auth:
        ApiKeyRequired: true
        ResourcePolicy:
          CustomStatements:
            - Effect: Allow
              Principal: "*"
              Action: execute-api:Invoke
              Resource: "arn:aws:execute-api:*:*:*/*/OPTIONS/*"
            - Effect: Allow
              Principal: "*"
              Action: execute-api:Invoke
              Resource: "arn:aws:execute-api:*:*:*/*/POST/*"
      GatewayResponses:
        DEFAULT_4XX:
          ResponseParameters:
            Headers:
              Access-Control-Allow-Origin: "'*'"
              Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        DEFAULT_5XX:
          ResponseParameters:
            Headers:
              Access-Control-Allow-Origin: "'*'"
              Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
      MinimumCompressionSize: 1024
      BinaryMediaTypes:
        - "*/*"
      # Optimizaciones de performance
      MethodSettings:
        - ResourcePath: "/*"
          HttpMethod: "*"
          ThrottlingRateLimit: 200
          ThrottlingBurstLimit: 500
          DataTraceEnabled: false
          MetricsEnabled: false

  ApiKey:
    Type: AWS::ApiGateway::ApiKey
    Properties:
      Enabled: true
      Name: CreditSimApiKey

  UsagePlan:
    Type: AWS::ApiGateway::UsagePlan
    Properties:
      UsagePlanName: CreditSimUsagePlan
      ApiStages:
        - ApiId: !Ref CreditSimApi
          Stage: !Ref CreditSimApi.Stage
      Throttle:
        RateLimit: 200
        BurstLimit: 500

  UsagePlanKey:
    Type: AWS::ApiGateway::UsagePlanKey
    Properties:
      KeyId: !Ref ApiKey
      KeyType: API_KEY
      UsagePlanId: !Ref UsagePlan

########################
# RDS PostgreSQL (Simple)
########################
  DBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: creditsim-db-final
      Engine: postgres
      EngineVersion: '15.8'
      DBInstanceClass: db.t3.micro
      AllocatedStorage: 20
      MasterUsername: postgres
      MasterUserPassword: CreditSim2024!
      DBName: creditsim
      PubliclyAccessible: true
      BackupRetentionPeriod: 0
      DeletionProtection: false

########################
# SQS + DLQ
########################
  RiskDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: creditsim-risk-audit-dlq

  RiskQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: creditsim-risk-audit-queue
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt RiskDLQ.Arn
        maxReceiveCount: 3

########################
# IAM
########################
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: SQSAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - sqs:SendMessage
                  - sqs:ReceiveMessage
                  - sqs:DeleteMessage
                  - sqs:GetQueueAttributes
                Resource:
                  - !GetAtt RiskQueue.Arn
                  - !GetAtt RiskDLQ.Arn

########################
# Lambda Functions
########################
  CreditSimLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: creditsim-simulate
      Runtime: python3.11
      Handler: app.handler
      Role: !GetAtt LambdaRole.Arn
      Timeout: 30
      MemorySize: 1024  # Más memoria = más CPU = menos latency
      CodeUri: ./backend/CreditSimLambda
      Environment:
        Variables:
          QUEUE_URL: !Ref RiskQueue
          CONNECTION_STRING: !Sub 'postgresql+pg8000://postgres:CreditSim2024!@${DBInstance.Endpoint.Address}:5432/creditsim'
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /simulate
            Method: post
            RestApiId: !Ref CreditSimApi
        OptionsEvent:
          Type: Api
          Properties:
            Path: /simulate
            Method: options
            RestApiId: !Ref CreditSimApi
            Auth:
              ApiKeyRequired: false
        # Warming event - mantiene lambda caliente
        WarmingEvent:
          Type: Schedule
          Properties:
            Schedule: rate(4 minutes)
            Input: '{"warmup": true}'

  RiskAuditLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: creditsim-risk-audit
      Runtime: python3.11
      Handler: app.handler
      Role: !GetAtt LambdaRole.Arn
      Timeout: 30
      MemorySize: 512
      CodeUri: ./backend/RiskAuditLambda
      Environment:
        Variables:
          CONNECTION_STRING: !Sub 'postgresql+pg8000://postgres:CreditSim2024!@${DBInstance.Endpoint.Address}:5432/creditsim'
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt RiskQueue.Arn
            BatchSize: 1



########################
# Outputs
########################
Outputs:
  ApiUrl:
    Description: URL del API Gatewayy
    Value: !Sub 'https://${CreditSimApi}.execute-api.${AWS::Region}.amazonaws.com/prod'
  
  CloudFrontUrl:
    Description: URL del frontend
    Value: !GetAtt CloudFront.DomainName
  
  ApiKeyValue:
    Description: API Key para autenticación
    Value: !Ref ApiKey
  
  DBEndpoint:
    Description: RDS PostgreSQL Endpoint
    Value: !GetAtt DBInstance.Endpoint.Address
